# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/images/user_images'),
        ),
    ]
